### ISSUE TITLE
No Fullscreen on FireTV Stick

### ISSUE THREAD

**Issue by Cona87** [truefedex/tv-bro#120] opened 2022-11-20 07:53 UTC
When I try to play a video in full screen they don't go full screen. The videos just fill about a third of the screen and are no bigger than without full screen. Any feedback/suggestions would be greatly appreciated.

**Comment by truefedex** [comment] 2022-11-20 16:33
Duplicate of https://github.com/truefedex/tv-bro/issues/24. Currently unfortunately still no solution.

**Closed by truefedex** 2022-11-20 16:33 UTC
