### ISSUE TITLE
Zoom in video files 

### ISSUE THREAD

**Issue by aaref1234** [truefedex/tv-bro#144] opened 2023-02-06 01:51 UTC
I used to enlarge video files in different sites, but now when I press the video zoom button, nothing happens at all, and the video plays in a small window .

**Comment by MailYouLater** [comment] 2023-02-06 04:46
This looks like a duplicate of #135 to me.
That issue is caused by the current version (109) of the Android System WebView component.  As a workaround, you can uninstall WebView updates, effectively reverting it back to whatever version of WebView came on your Android TV device.

If you open TV Bro's settings, and go to the VERSION & UPDATES tab, you can check to see what version of Android System WebView you're on.

**Closed** 2023-02-06 06:59 UTC

**Comment by aaref1234** [comment] 2023-02-06 09:45
Thank you .
The problem has been resolved .
